name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['22', '23', '24']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java-version }}
      - name: Maven build
        run: cd test && ./mvnw --batch-mode --no-transfer-progress verify --file pom.xml && java -jar target/benchmarks.jar 